### ISSUE TITLE
Guava Required

### ISSUE THREAD

**Issue by onyxmueller** [mttkay/ignition#2]
Classes within ignition-support (e.g., AbstractCache) are dependent upon Guava (AKA Google Collections library).  This should be documented/communicated.

**Comment by mttkay** [comment]
Yes we're lacking docs for all the submodules. I'm currently working on sample applications, which I believe serve best as documentation, but I'll write up some basic info on the front page too. Thanks.

**Comment by onyxmueller** [comment]
No problem.  Yeah, I think sample applications will best serve as documentation as well.  Thanks for putting this project together.
