### ISSUE TITLE
No clear instructions on using it as a library for an Android project

### ISSUE THREAD

**Issue by nubela** [mttkay/ignition#3]
I'm trying to use ignition-core as a library for my Android app. I tried following instructions, and got as far as gradle eclipse, and having the .project files imported into eclipse from <Workspace>/ignition/ignition-core, but it seems that the Android project does not find the classes, despite having it added as a project requirement in the build path settings.

I looked deeper at your project struction, and realised that ignition-core-lib is an android app project of which I believe I should be including, and in there, lies a build.gradle too. I am however unable to use that gradle build path. Perhaps it would be better if clearer instructions could be posted on this? Thanks!

PS: There are some dead links in the readme too. Cheers! PS: Nice work btw.

**Comment by mttkay** [comment]
Hey there, I've updated the front page and created a wiki page with instructions. Can you give me feedback on whether you think the instructions are clear enough and worked for you? Thanks!
