### ISSUE TITLE
Warning: Cookie Rejected

### ISSUE THREAD

**Issue by zakdances** [mttkay/ignition#6]
I am getting 3 "Cookie Rejected" errors during the build test (Building ignition-location-tests 0.1-SNAPSHOT)...this doesn't seem to effect the final result because I am getting a clear SUCCESS summary, but I do think it's strange. Should I post the full error messages here?

**Comment by mttkay** [comment]
Yes please let me see the error message. Is this when trying to access nexus.qype.com?

**Comment by mttkay** [comment]
We tested the ignition-1.0 release build on a fresh Maven installation, works.
